name: "KiCad CI/CD for Horticulture-LED"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'Horticulture-LED/*.sch'
      - 'Horticulture-LED/*.kicad_pcb'
      - 'Horticulture-LED/*.kibot.yaml'
      - 'Horticulture-LED/Makefile'
      - '.github/workflows/horticulture_led.yml'
  pull_request:
    paths:
      - 'Horticulture-LED/*.sch'
      - 'Horticulture-LED/*.kicad_pcb'
      - 'Horticulture-LED/*.kibot.yaml'
      - 'Horticulture-LED/Makefile'
      - '.github/workflows/horticulture_led.yml'
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Fabrication:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v1
      with:
        # Required - kibot config file
        config: Horticulture-LED/horticulture_led.kibot.yaml
        # optional - prefix to output defined in config
        dir: Horticulture-LED/Fabrication
        # optional - schematic file
        schema: 'Horticulture-LED/Horticulture.sch'
        # optional - PCB design file
        board: 'Horticulture-LED/Horticulture.kicad_pcb'
    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Fabrication
        path: |
          Horticulture-LED/Fabrication/
        if-no-files-found: warn
    - name: Prepare release files
      run: |
        cd /home/runner/work/Horticulture-PCB/Horticulture-PCB/Horticulture-LED/Fabrication
        cp Gerbers -R /tmp/Plot
        cp Schematic.pdf /tmp/Schematic-Horticulture-LED-PCB.pdf
        cp BoM/*ibom* /tmp/iBom-Horticulture-LED-PCB.html
        ls 3D
        cp 3D/*.step /tmp/Horticulture-LED-PCB.step
        cd /tmp
        zip -r Plot-Horticulture-LED-PCB.zip Plot
        echo prepared for release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with: 
        files: |
          /tmp/Plot-Horticulture-LED-PCB.zip
          /tmp/Schematic-Horticulture-LED-PCB.pdf
          /tmp/iBom-Horticulture-LED-PCB.html
          /tmp/Horticulture-LED-PCB.step
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


